# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - Rilung

on:
  push:
    branches:
      - index

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'   

      
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      
      - name: Run tests
        run: vendor/bin/phpunit --testdox || echo "No tests found, skipping"

    
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php-app
          path: .
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: php-app

  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Rilung"   
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .

          
